import multer from "multer";

// const upload=multer({dest:"images"});

const storage=multer.diskStorage({
    destination: "images/",
    filename: (req, file, cb) =>{ //cb: callback function
        // The filename is generated by concatenating the current timestamp (Date.now()) with the original 
        // name of the uploaded file (file.originalname).
        cb(null, Date.now() + "-" + file.originalname);
    } });
// multer({storage}) creates an instance of multer with the specified storage configuration, 
// which will be used to handle file uploads in the routes.
const upload=multer({storage});

export default upload;
